pipeline {
    agent {
        docker {
            reuseNode true
            image 'docker-sdda-dev/maven-openjdk:3.6.3-11.0.14'
            registryUrl 'https://fx-artifactory.uk.db.com/'
            registryCredentialsId '142900-1-docker_registry_user'
            args '-v /u01/jenkins/m2-repo:/m2-repo:z'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
