pipeline {
    agent {
        docker {
            reuseNode true
            image 'dk1755-a/mvn-3.5.4-jdk-8.0.271.2'
            args '-v /u01/jenkins/m2-repo:/m2-repo:z'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
